name: Code security scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '11 22 * * 2'

permissions:
  contents: read
  security-events: write

jobs:
  codeql:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout locked source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@f2f7fd574d1c3d1a39f788b46bbf73d8cfb346f0 # v3.29.10
        with:
          languages: javascript-typescript
      - name: Analyze
        uses: github/codeql-action/analyze@f2f7fd574d1c3d1a39f788b46bbf73d8cfb346f0 # v3.29.10

